# npm run api-docs
# "prestart": "npm run api-docs",
openapi: 3.0.0
info:
  version: 1.0.0
  title: Mindi_API
  description: Mindi의 API 명세서
servers:
  - url: 'http://localhost:5001/api/'
paths:
  /diaries:
    post:
      $ref: './paths/diary.yaml#/Post'
    put:
      $ref: './paths/diary.yaml#/Update'
    delete:
      $ref: './paths/diary.yaml#/Delete'
  /diaries?date={date}:
    get:
      $ref: './paths/diary.yaml#/GetAList'
  /diaries/{id}:
    get:
      $ref: './paths/diary.yaml#/GetADiary'
components:
  schemas:
    diary:
      $ref: './components/schemas/diary.yaml'
