version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - "redis-server"

  client:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - server

  server:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - "5001:5000"
    depends_on:
      - redis