version: "3"
services:
#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    command:
#      - "redis-server"
  nginx:
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile.dev
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - ai

  client:
    build:
      context: ../front
      dockerfile: ../front/Dockerfile.dev
    container_name: client-container
    ports:
      - "3001:3001"
    depends_on:
#      - redis
      - server
      - ai

  server:
    build:
      context: ../back
      dockerfile: ../back/Dockerfile.dev
    container_name: server-container
    ports:
      - "5001:5001"
#    depends_on:
#      - redis
  ai:
    build:
      context: ../ai
      dockerfile: ../ai/Dockerfile.dev
    container_name: ai-container
    ports:
      - "8000:8000"